### ISSUE TITLE
retrieving many-to-many relationships

### ISSUE THREAD

**Issue by omarjebari** [vuex-orm/vuex-orm-examples#1]
Hi,

I am receiving the following error when trying to retrieve a man-to-many relationship...
"TypeError: Cannot read property 'data' of undefined"

My models are setup like so:

```js
export default class User extends Model {
    static get entity () {
        return 'users'
    }
    static fields () {
        return {
            id: this.attr(null),
            name: this.attr(''),
            email: this.attr(''),
            roles: this.belongsToMany(Role, RoleUser, 'user_id', 'role_id')
        }
    }
}

export default class Role extends Model {
    static get entity () {
        return 'roles'
    }
    static fields () {
        return {
            id: this.attr(null),
            name: this.attr(''),
            permissions: this.belongsToMany(Permission, RolePermission, 'role_id', 'permission_id')
        }
    }
}

export default class Permission extends Model {
    static get entity () {
        return 'permissions'
    }
    static fields () {
        return {
            id: this.attr(null),
            name: this.attr(''),
        }
    }
}

export default class RoleUser extends Model {
    static get entity () {
        return 'role_users'
    }
    static primaryKey () {
        return ['role_id', 'user_id']
    }
    static fields () {
        return {
            role_id: this.attr(null),
            user_id: this.attr(null)
        }
    }
}

export default class RolePermission extends Model {
    static get entity () {
        return 'role_permissions'
    }
    static primaryKey () {
        return ['role_id', 'permission_id'];
    }
    static fields () {
        return {
            role_id: this.attr(null),
            permission_id: this.attr(''),
        }
    }
}
```

Inside my component's created() method i am calling to create the user data:

```js
const data = {
                    id: 1,
                    name: 'John Doe',
                    email: 'test@test.com',
                    roles: [
                        {
                            id: 1,
                            name: 'admin',
                            permissions: [
                                {
                                    id: 1,
                                    name: 'create user'
                                }
                            ]
                        },
                    ]
                };

                this.$store.dispatch('entities/users/create', { data });
```

If i then make a computed property in the same component:

```js
users() {
    return this.$store.getters['entities/users/all']();
}
```

Then this works OK!!

But if i try to get the role relation:

```js
users() {
    return this.$store.getters['entities/users/query']()
                    .with('roles')
                    .get();
}
```

It gives the error above!!!

**Comment by kiaking** [comment]
@omarjebari Hi! That error seems like you're not registering models to the database...? Have you register all of your models?

**Comment by omarjebari** [comment]
Ultimately the server will respond with something like the content below and i want it to populate my models with the appropriate relationships:

`[{"id":1,"name":"omar","email":"oj@gmail.com","email_verified_at":null,"created_at":null,"updated_at":null,"roles":[{"id":1,"name":"superuser","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"model_id":1,"role_id":1,"model_type":"App\\User"},"permissions":[{"id":1,"name":"create user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":1,"permission_id":1}},{"id":2,"name":"read user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":1,"permission_id":2}},{"id":3,"name":"update user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":1,"permission_id":3}},{"id":4,"name":"delete user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":1,"permission_id":4}}]}]},{"id":2,"name":"dave smith","email":"ds@gmail.com","email_verified_at":null,"created_at":null,"updated_at":null,"roles":[{"id":2,"name":"admin","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"model_id":2,"role_id":2,"model_type":"App\\User"},"permissions":[{"id":1,"name":"create user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":1}},{"id":2,"name":"read user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":2}},{"id":3,"name":"update user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":3}},{"id":4,"name":"delete user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":4}}]}]},{"id":3,"name":"testoj","email":"test1@gmail.com","email_verified_at":null,"created_at":"2018-10-22 15:40:25","updated_at":"2018-10-22 15:40:25","roles":[{"id":2,"name":"admin","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"model_id":3,"role_id":2,"model_type":"App\\User"},"permissions":[{"id":1,"name":"create user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":1}},{"id":2,"name":"read user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":2}},{"id":3,"name":"update user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":3}},{"id":4,"name":"delete user","guard_name":"web","created_at":null,"updated_at":null,"pivot":{"role_id":2,"permission_id":4}}]}]}]`

**Comment by omarjebari** [comment]
Ultimately the data i am trying to load from the server (which will populate the users/roles/perms) is: 

```
[
  {
    "id": 1,
    "name": "omar jebari",
    "email": "oj@gmail.com",
    "roles": [
      {
        "id": 1,
        "name": "superuser",
        "permissions": [
          {
            "id": 1,
            "name": "create user"
          },
          {
            "id": 2,
            "name": "read user"
          },
          {
            "id": 3,
            "name": "update user"
          },
          {
            "id": 4,
            "name": "delete user"
          }
        ]
      }
    ]
  },
  {
    "id": 2,
    "name": "dave smith",
    "email": "ds@gmail.com",
    "roles": [
      {
        "id": 2,
        "name": "admin",
        "permissions": [
          {
            "id": 1,
            "name": "create user"
          },
          {
            "id": 2,
            "name": "read user"
          },
          {
            "id": 3,
            "name": "update user"
          },
          {
            "id": 4,
            "name": "delete user"
          }
        ]
      }
    ]
  },
  {
    "id": 3,
    "name": "testoj",
    "email": "test1@gmail.com",
    "roles": [
      {
        "id": 2,
        "name": "admin",
        "permissions": [
          {
            "id": 1,
            "name": "create user"
          },
          {
            "id": 2,
            "name": "read user"
          },
          {
            "id": 3,
            "name": "update user"
          },
          {
            "id": 4,
            "name": "delete user"
          }
        ]
      }
    ]
  }
]
```

**Comment by kiaking** [comment]
OK, the following tests are passing. Could you take a look and see what is the differences from your setup?

```js
it.only('can resolve nested belongs to relation', async () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null),
        roles: this.belongsToMany(Role, RoleUser, 'user_id', 'role_id')
      }
    }
  }

  class Role extends Model {
    static entity = 'roles'

    static fields () {
      return {
        id: this.attr(null),
        permissions: this.belongsToMany(Permission, RolePermission, 'role_id', 'permission_id')
      }
    }
  }

  class Permission extends Model {
    static entity = 'permissions'

    static fields () {
      return {
        id: this.attr(null)
      }
    }
  }

  class RoleUser extends Model {
    static entity = 'role_users'

    static primaryKey = ['role_id', 'user_id']

    static fields () {
      return {
        role_id: this.attr(null),
        user_id: this.attr(null)
      }
    }
  }

  class RolePermission extends Model {
    static entity = 'role_permissions'

    static primaryKey = ['role_id', 'permission_id']

    static fields () {
      return {
        role_id: this.attr(null),
        permission_id: this.attr('')
      }
    }
  }

  createStore([{ model: User }, { model: Role }, { model: Permission }, { model: RoleUser }, { model: RolePermission }])

  const data = [
    {
      'id': 1,
      'roles': [
        {
          'id': 1,
          'permissions': [{ 'id': 1 }, { 'id': 2 }, { 'id': 3 }, { 'id': 4 }]
        }
      ]
    },
    {
      'id': 2,
      'roles': [
        {
          'id': 2,
          'permissions': [{ 'id': 1 }, { 'id': 2 }, { 'id': 3 }, { 'id': 4 }]
        }
      ]
    }
  ]

  await User.create({ data })

  const users = User.query().with('roles.permissions').get()

  expect(users[0].id).toBe(1)
  expect(users[0].roles.length).toBe(1)
  expect(users[0].roles[0].id).toBe(1)
  expect(users[0].roles[0].permissions.length).toBe(4)
  expect(users[0].roles[0].permissions[0].id).toBe(1)
  expect(users[0].roles[0].permissions[1].id).toBe(2)

  expect(users[1].id).toBe(2)
  expect(users[1].roles.length).toBe(1)
  expect(users[1].roles[0].id).toBe(2)
  expect(users[1].roles[0].permissions.length).toBe(4)
  expect(users[1].roles[0].permissions[0].id).toBe(1)
  expect(users[1].roles[0].permissions[1].id).toBe(2)
})
```

**Comment by omarjebari** [comment]
Many thanks for looking into this.

I have coded the create and get of data like this (as await in your example didnt work for me, got a build error).

```
store.dispatch('entities/users/create', { data })
                .then(entities => {

                    // If i console.log(entities) here i get users with undefined roles

                    const users = store.getters['entities/users/query']().with('roles.permissions').get();

                    // If i console.log(users) here i also get users with undefined roles

                });
```

The only other difference was that i had to replace:

`static primaryKey = ['role_id', 'user_id']
`
with: 

```
    static primaryKey () {
        return ['role_id', 'user_id']
    }
```

The only thing that i am not specifically calling is:

`createStore([{ model: User }, { model: Role }, { model: Permission }, { model: RoleUser }, { model: RolePermission }])`

but i'm guessing that i don't need to use this line as my model/models are initialised in database.js and index.js in  /store.
Btw if vuexORM is available by a cdn then i will load my code into CodePen to make this easier.

**Comment by kiaking** [comment]
For the primary key, you should set it as a getter.

```js
static get primaryKey = ['role_id', 'user_id']
```

For this part;

```js
                .then(entities => {

                    // If i console.log(entities) here i get users with undefined roles
```

It's expected that the roles to be `undefined` because, at this moment, all of the records are normalized and decoupled from each other.

For this part;

```js
                    const users = store.getters['entities/users/query']().with('roles.permissions').get();

                    // If i console.log(users) here i also get users with undefined roles
```

It's indeed wired why you don't get roles...

> Btw if vuexORM is available by a cdn then i will load my code into CodePen to make this easier.

YES! You can directly download from https://unpkg.com/@vuex-orm/core.

[See more detail at here](https://vuex-orm.github.io/vuex-orm/guide/prologue/installation.html#direct-download-cdn).

**Comment by omarjebari** [comment]
It is working now!
The problem was the primary keys not being set as getters!!
Thank you so much for your help with this. I am setting up this piece of work as a demo to my company to encourage them to use VuexORM :)

**Comment by kiaking** [comment]
Wonderful to hear that!

> Thank you so much for your help with this. I am setting up this piece of work as a demo to my company to encourage them to use VuexORM :)

I hope you'll succeed!
