### ISSUE TITLE
how to include vuex-orm-localforage?

### ISSUE THREAD

**Issue by jfqd** [vuex-orm/vuex-orm-examples#2]
I am wondering how to include `vuex-orm-localforage` into this demo app.

I tried to include the following code from the readme

```js
import VuexORMLocalForage from 'vuex-orm-localforage'

const database = new VuexORM.Database()

VuexORM.use(VuexORMLocalForage, {
  database
})
```

into `src/store/index.js` so it now looks like:

```js
import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM from '@vuex-orm/core'
import VuexORMLocalForage from 'vuex-orm-localforage'
import database from '@/database'

Vue.use(Vuex)

VuexORM.use(VuexORMLocalForage, {
  database
})

const store = new Vuex.Store({
  namespaced: true,
  plugins: [VuexORM.install(database)]
})

export default store
```

But I am not able to enter any user name nor todo. Maybe this approach was to naiv, but how can it be accomplished?

**Comment by kiaking** [comment]
@jfqd Hi! Thank you for the report! I don't maintain `vuex-orm-localforage` so not sure what is wrong. Have you tried opening an issue at localforage repo?

**Comment by jfqd** [comment]
@kiaking Thank you for your reply! I forked the repo, added the code and created an [issue](https://github.com/eldomagan/vuex-orm-localforage/issues/7) on the `vuex-orm-localforage` project.

**Comment by kiaking** [comment]
@jfqd Great! I hope you get answer there. Let me know if there's anything else 👍
